---
mqtt_host: homeassistant.n1mtp.com

frigate_server_ip: 192.168.1.209

deck:
  enabled: true
  username: admin
  ip_address: 192.168.1.185

doorbell:
  enabled: true
  username: admin
  ip_address: 192.168.1.216

floodlight:
  enabled: true
  username: admin
  ip_address: 192.168.1.170

