---
- name: restart ntfy
  become: yes
  ansible.builtin.systemd_service:
    name: ntfy
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart nginx
  become: yes
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart dnsmasq
  become: yes
  ansible.builtin.systemd_service:
    name: dnsmasq
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart journald
  become: yes
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted
    enabled: yes
    daemon_reload: yes
