---
- name: Install prometheus-node-exporter
  become: yes
  ansible.builtin.apt:
    update_cache: true
    name:
      - prometheus-node-exporter
      - prometheus-node-exporter-collectors

- name: Place node-exporter config
  become: true
  ansible.builtin.template:
    src: prometheus-node-exporter.j2
    dest: /etc/default/prometheus-node-exporter
    owner: root
    group: root
    mode: 0600
    backup: yes
  notify: Restart node-exporter

- name: Start and enable node-exporter
  become: true
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    state: started
    enabled: true
    daemon_reload: yes
