---
- name: Create /etc/systemd/journald.conf.d directory
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Copy custom journald config
  ansible.builtin.copy:
    src: journald_custom.conf
    dest: /etc/systemd/journald.conf.d/custom.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - restart journald
